add php lint

diff --git a/.husky/pre-commit b/.husky/pre-commit
--- a/.husky/pre-commit
+++ b/.husky/pre-commit
@@ -1,10 +1,10 @@
 #!/bin/sh
 
-# echo "🔧 Running production build before commit..."
+echo "🔧 Running production build before commit..."
 
-# if ! npm run lint; then
-#   echo "❌ Build failed. Fix errors before committing!"
-#   exit 1
-# fi
+if ! npm run build; then
+  echo "❌ Build failed. Fix errors before committing!"
+  exit 1
+fi
 
-# echo "✅ Build success. Running spell check..."
+echo "✅ Build success. Running spell check..."
